[package]
name = "waithook"
version = "0.1.0"
authors = ["Pavel Evstigneev <pavel.evst@gmail.com>"]

[dependencies]
env_logger = "*"
hyper = "0.9.10"
rustc-serialize = "0.3.19"
time = "0.1"

websocket = { git = "https://github.com/Paxa/rust-websocket.git" }
#websocket = { path = "./rust-websocket" }
